
spring:
  datasource:
    url: jdbc:postgresql://104.154.17.176:5432/irmdb
    username: irmuser
    password: irmuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: tru
  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: U9PiGZPTB8o4r9soYEDmyNTJNPryzR9tGJDmt7VP3nGmKYbCDhpo1Ht6UqJchIC8onIlEGZs/F1u+I9+Ce7mVA== # base64 of 256-bit key
  expiration: 3600000 # 1 hour in milliseconds